package com.tonyk.ws;

public class Constants {

	public static final String[] LEVEL_WORD = new String[] {
		"STRAWBERRY,WATERMELON,AVOCADO,COCONUT,PEANUT,PAPAYA,ORANGE,BANANA,DURIAN,CHERRY,LONGAN,GRAPE,APPLE,MANGO,LEMON,PEACH,GUAVA,PEAR,PLUM,LIME,KIWI,FIG",
		"SHOULDER,STOMACH,FINGER,TONGUE,ANKLE,CHEST,WAIST,MOUTH,CHEEK,ELBOW,THIGH,THUMB,BRAIN,HAND,NECK,BACK,CHIN,HAIR,FOOT,KNEE,FACE,NOSE,HIP,ARM,LEG,EAR,LIP,EYE",
		"BUTTERFLY,ABALONE,PEACOCK,RABBIT,CANARY,DONKEY,PIGEON,SPIDER,GIBBON,EAGLE,PANDA,SHARK,SNAKE,TIGER,WOLF,DUCK,SWAN,CRAB,LION,PUMA,ANT,BEE,FOX,PIG,DOG,CAT",
		"SPARROW,VULTURE,FEATHER,OSTRICH,PENGUIN,TURKEY,PIGEON,FALCON,PARROT,TALON,CRANE,HERON,STORK,EAGLE,GOOSE,CROW,DOVE,NEST,DUCK,SWAN,OWL",
		"CENTIPEDE,COCKROACH,PARASITE,MOSQUITO,LADYBUG,SCORPION,CRICKET,SPIDER,BEETLE,SNAIL,SWARM,FLEA,WORM,MOTH,WASP,ANT,FLY,BEE" };

	public static final String[] LEVEL_TITLE = new String[] {
		"FRUIT",
		"BODYPART",
		"ANIMAL",
		"BIRD",
		"INSECT"
	};
}
